### PR TITLE
OOP agent rewrite

### PR DESCRIPTION
**Pull request by whitx**
# Description

Redesign the code of the windows agent, to be more readable and functional
# Impacts

windows agent
(tested with PEAP/EAP-TLS, Open mode)
# Delete branch after merge

YES 
## Enhancements
- Make code clearer and stop fetching 10time the profile

### CODE REVIEW

**Comment by whitx** [comment]
@fdurand ping

**Comment by whitx** [comment]
To add: link with commit with the new agent to merge into pf codebase. This part might need to be reworked/change tbd.

**Comment by whitx** [comment]
New agent: https://github.com/whitx/packetfence/commit/c271cbb6fc1f0c4ac1361c6779984e52b0c883f8

**Comment by whitx** [comment]
This should be merged when this one is:
https://github.com/inverse-inc/packetfence/pull/1129

**Comment by extrafu** [comment]
Not relevant anymore.

**Pull request closed without merging**
